version: "3"

services:
    backend:
        build: nodejs-server-server/
        ports:
            - "8080:8080"
    ui:
        build: webui/
        ports:
            - "8081:8080"
        volumes:
            - $pwd:/app
